const elementsData = [
  // Dados de cada elemento da tabela
  
  {
    "number": 1,
    "name": "Hidrogênio",
    "symbol": "H",
    "mass": "1.008 u",
    "state": "Gasoso",
    "meltingPoint": "-259.1 °C",
    "boilingPoint": "-252.9 °C",
    "electronegativity": "2.20",
    "description": "O elemento mais leve e abundante do universo! É o combustível das estrelas e do Sol. Na Terra, adora se juntar com o oxigênio para formar a água que a gente bebe."
  },
  {
    "number": 2,
    "name": "Hélio",
    "symbol": "He",
    "mass": "4.002 u",
    "state": "Gasoso",
    "meltingPoint": "-272.2 °C",
    "boilingPoint": "-268.9 °C",
    "electronegativity": "N/A",
    "description": "O gás que faz a sua voz ficar engraçada e fina quando você inala! Ele é tão leve que sobe até o espaço e é usado para fazer balões flutuarem."
  },
  {
    "number": 3,
    "name": "Lítio",
    "symbol": "Li",
    "mass": "6.94 u",
    "state": "Sólido",
    "meltingPoint": "180.5 °C",
    "boilingPoint": "1342 °C",
    "electronegativity": "0.98",
    "description": "O coração das baterias! É um metal super leve que guarda a energia do seu celular, tablet e até de carros elétricos."
  },
  {
    "number": 4,
    "name": "Berílio",
    "symbol": "Be",
    "mass": "9.01 u",
    "state": "Sólido",
    "meltingPoint": "1287 °C",
    "boilingPoint": "2470 °C",
    "electronegativity": "1.57",
    "description": "Um metal raro e resistente que adora aventuras espaciais. É usado em telescópios e naves que viajam pelas estrelas."
  },
  {
    "number": 5,
    "name": "Boro",
    "symbol": "B",
    "mass": "10.81 u",
    "state": "Sólido",
    "meltingPoint": "2075 °C",
    "boilingPoint": "4000 °C",
    "electronegativity": "2.04",
    "description": "Um mineral usado para fazer o vidro do forno resistir ao calor sem quebrar. Também deixa as fibras de vidro super resistentes."
  },
  {
    "number": 6,
    "name": "Carbono",
    "symbol": "C",
    "mass": "12.01 u",
    "state": "Sólido",
    "meltingPoint": "3550 °C",
    "boilingPoint": "4827 °C",
    "electronegativity": "2.55",
    "description": "O elemento da vida! Tudo o que é vivo na Terra tem carbono. Ele forma desde o grafite do lápis até o diamante."
  },
  {
    "number": 7,
    "name": "Nitrogênio",
    "symbol": "N",
    "mass": "14.01 u",
    "state": "Gasoso",
    "meltingPoint": "-210.0 °C",
    "boilingPoint": "-195.8 °C",
    "electronegativity": "3.04",
    "description": "Fica escondido no ar que respiramos, mas é fundamental para as plantas crescerem e para congelar coisas muito rápido."
  },
  {
    "number": 8,
    "name": "Oxigênio",
    "symbol": "O",
    "mass": "16.00 u",
    "state": "Gasoso",
    "meltingPoint": "-218.8 °C",
    "boilingPoint": "-183.0 °C",
    "electronegativity": "3.44",
    "description": "O fôlego da vida! Sem ele a gente não conseguiria respirar. Ele também ajuda o fogo a queimar e faz a água existir."
  },
  {
    "number": 9,
    "name": "Flúor",
    "symbol": "F",
    "mass": "19.00 u",
    "state": "Gasoso",
    "meltingPoint": "-219.6 °C",
    "boilingPoint": "-188.1 °C",
    "electronegativity": "3.98",
    "description": "O protetor do seu sorriso! Ele é adicionado na pasta de dente para fortalecer os dentes contra cáries."
  },
  {
    "number": 10,
    "name": "Neônio",
    "symbol": "Ne",
    "mass": "20.18 u",
    "state": "Gasoso",
    "meltingPoint": "-248.6 °C",
    "boilingPoint": "-246.1 °C",
    "electronegativity": "N/A",
    "description": "Gosta de brilhar! É o gás que ilumina letreiros luminosos coloridos nas cidades."
  },
  {
    "number": 11,
    "name": "Sódio",
    "symbol": "Na",
    "mass": "22.99 u",
    "state": "Sólido",
    "meltingPoint": "97.8 °C",
    "boilingPoint": "883 °C",
    "electronegativity": "0.93",
    "description": "Junto com o cloro forma o sal de cozinha. É um metal que reage fortemente com a água."
  },
  {
    "number": 12,
    "name": "Magnésio",
    "symbol": "Mg",
    "mass": "24.31 u",
    "state": "Sólido",
    "meltingPoint": "650 °C",
    "boilingPoint": "1091 °C",
    "electronegativity": "1.31",
    "description": "O elemento do brilho intenso. Usado em fogos de artifício e importante para o funcionamento do corpo humano."
  },
  {
    "number": 13,
    "name": "Alumínio",
    "symbol": "Al",
    "mass": "26.98 u",
    "state": "Sólido",
    "meltingPoint": "660.3 °C",
    "boilingPoint": "2470 °C",
    "electronegativity": "1.61",
    "description": "Metal leve e resistente presente em latinhas, papel-alumínio e diversos utensílios."
  },
  {
    "number": 14,
    "name": "Silício",
    "symbol": "Si",
    "mass": "28.09 u",
    "state": "Sólido",
    "meltingPoint": "1414 °C",
    "boilingPoint": "3265 °C",
    "electronegativity": "1.90",
    "description": "O cérebro dos computadores! Usado para fabricar chips eletrônicos e tecnologia digital."
  },
  {
    "number": 15,
    "name": "Fósforo",
    "symbol": "P",
    "mass": "30.97 u",
    "state": "Sólido",
    "meltingPoint": "44.1 °C",
    "boilingPoint": "280.5 °C",
    "electronegativity": "2.19",
    "description": "Importante para ossos e energia do corpo, além de estar presente em fósforos."
  },
  {
    "number": 16,
    "name": "Enxofre",
    "symbol": "S",
    "mass": "32.06 u",
    "state": "Sólido",
    "meltingPoint": "115.2 °C",
    "boilingPoint": "444.6 °C",
    "electronegativity": "2.58",
    "description": "Amarelo e com cheiro forte, é usado em borracha e produtos industriais."
  },
  {
    "number": 17,
    "name": "Cloro",
    "symbol": "Cl",
    "mass": "35.45 u",
    "state": "Gasoso",
    "meltingPoint": "-101.5 °C",
    "boilingPoint": "-34.0 °C",
    "electronegativity": "3.16",
    "description": "Muito usado na limpeza e tratamento de água, sendo essencial para a saúde pública."
  },
  {
    "number": 18,
    "name": "Argônio",
    "symbol": "Ar",
    "mass": "39.95 u",
    "state": "Gasoso",
    "meltingPoint": "-189.3 °C",
    "boilingPoint": "-185.8 °C",
    "electronegativity": "N/A",
    "description": "Gás nobre que não reage facilmente, usado em lâmpadas e ambientes controlados."
  },
  {
    "number": 19,
    "name": "Potássio",
    "symbol": "K",
    "mass": "39.10 u",
    "state": "Sólido",
    "meltingPoint": "63.5 °C",
    "boilingPoint": "759 °C",
    "electronegativity": "0.82",
    "description": "Essencial para músculos e coração, encontrado em alimentos como bananas."
  },
  {
    "number": 20,
    "name": "Cálcio",
    "symbol": "Ca",
    "mass": "40.08 u",
    "state": "Sólido",
    "meltingPoint": "842 °C",
    "boilingPoint": "1484 °C",
    "electronegativity": "1.00",
    "description": "Fortalece ossos e dentes, sendo essencial para o corpo humano."
  },
  {
    "number": 21,
    "name": "Escândio",
    "symbol": "Sc",
    "mass": "44.96 u",
    "state": "Sólido",
    "meltingPoint": "1541 °C",
    "boilingPoint": "2836 °C",
    "electronegativity": "1.36",
    "description": "Metal leve e resistente usado em ligas para equipamentos esportivos e aeronaves."
  },
  {
    "number": 22,
    "name": "Titânio",
    "symbol": "Ti",
    "mass": "47.87 u",
    "state": "Sólido",
    "meltingPoint": "1668 °C",
    "boilingPoint": "3287 °C",
    "electronegativity": "1.54",
    "description": "Extremamente resistente e leve, usado em próteses, aviões e equipamentos espaciais."
  },
  {
    "number": 23,
    "name": "Vanádio",
    "symbol": "V",
    "mass": "50.94 u",
    "state": "Sólido",
    "meltingPoint": "1910 °C",
    "boilingPoint": "3407 °C",
    "electronegativity": "1.63",
    "description": "Fortalece ligas metálicas usadas em ferramentas e peças automotivas."
  },
  {
    "number": 24,
    "name": "Cromo",
    "symbol": "Cr",
    "mass": "52.00 u",
    "state": "Sólido",
    "meltingPoint": "1907 °C",
    "boilingPoint": "2671 °C",
    "electronegativity": "1.66",
    "description": "Dá brilho aos metais e protege contra corrosão."
  },
  {
    "number": 25,
    "name": "Manganês",
    "symbol": "Mn",
    "mass": "54.94 u",
    "state": "Sólido",
    "meltingPoint": "1246 °C",
    "boilingPoint": "2061 °C",
    "electronegativity": "1.55",
    "description": "Importante para a saúde e usado na produção de aço."
  },
  {
    "number": 26,
    "name": "Ferro",
    "symbol": "Fe",
    "mass": "55.85 u",
    "state": "Sólido",
    "meltingPoint": "1538 °C",
    "boilingPoint": "2862 °C",
    "electronegativity": "1.83",
    "description": "Essencial para construções e para o transporte de oxigênio no sangue."
  },
  {
    "number": 27,
    "name": "Cobalto",
    "symbol": "Co",
    "mass": "58.93 u",
    "state": "Sólido",
    "meltingPoint": "1495 °C",
    "boilingPoint": "2927 °C",
    "electronegativity": "1.88",
    "description": "Usado em pigmentos azuis e em baterias."
  },
  {
    "number": 28,
    "name": "Níquel",
    "symbol": "Ni",
    "mass": "58.69 u",
    "state": "Sólido",
    "meltingPoint": "1455 °C",
    "boilingPoint": "2913 °C",
    "electronegativity": "1.91",
    "description": "Presente em moedas, aço inoxidável e baterias."
  },
  {
    "number": 29,
    "name": "Cobre",
    "symbol": "Cu",
    "mass": "63.55 u",
    "state": "Sólido",
    "meltingPoint": "1084.6 °C",
    "boilingPoint": "2562 °C",
    "electronegativity": "1.90",
    "description": "Excelente condutor elétrico usado em fios e cabos."
  },
  {
    "number": 30,
    "name": "Zinco",
    "symbol": "Zn",
    "mass": "65.38 u",
    "state": "Sólido",
    "meltingPoint": "419.5 °C",
    "boilingPoint": "907 °C",
    "electronegativity": "1.65",
    "description": "Protege contra corrosão e é usado em suplementos e cosméticos."
  },
  {
    "number": 31,
    "name": "Gálio",
    "symbol": "Ga",
    "mass": "69.72 u",
    "state": "Sólido",
    "meltingPoint": "29.8 °C",
    "boilingPoint": "2204 °C",
    "electronegativity": "1.81",
    "description": "Tem o poder de derreter na sua mão! Um metal que vira líquido com o calor do corpo."
  },
  {
    "number": 32,
    "name": "Germânio",
    "symbol": "Ge",
    "mass": "72.63 u",
    "state": "Sólido",
    "meltingPoint": "938.3 °C",
    "boilingPoint": "2820 °C",
    "electronegativity": "2.01",
    "description": "Usado em tecnologia, como lentes de visão noturna e sensores térmicos."
  },
  {
    "number": 33,
    "name": "Arsênio",
    "symbol": "As",
    "mass": "74.92 u",
    "state": "Sólido",
    "meltingPoint": "817 °C",
    "boilingPoint": "614 °C",
    "electronegativity": "2.18",
    "description": "Conhecido por sua toxicidade, foi usado em venenos e também em componentes eletrônicos."
  },
  {
    "number": 34,
    "name": "Selênio",
    "symbol": "Se",
    "mass": "78.97 u",
    "state": "Sólido",
    "meltingPoint": "221 °C",
    "boilingPoint": "685 °C",
    "electronegativity": "2.55",
    "description": "Importante para o corpo humano e usado na indústria do vidro."
  },
  {
    "number": 35,
    "name": "Bromo",
    "symbol": "Br",
    "mass": "79.90 u",
    "state": "Líquido",
    "meltingPoint": "-7.2 °C",
    "boilingPoint": "58.8 °C",
    "electronegativity": "2.96",
    "description": "Um dos poucos elementos líquidos à temperatura ambiente, usado em retardantes de chama."
  },
  {
    "number": 36,
    "name": "Criptônio",
    "symbol": "Kr",
    "mass": "83.80 u",
    "state": "Gasoso",
    "meltingPoint": "-157.4 °C",
    "boilingPoint": "-153.4 °C",
    "electronegativity": "3.00",
    "description": "Gás nobre usado em iluminação e lasers especiais."
  },
  {
    "number": 37,
    "name": "Rubídio",
    "symbol": "Rb",
    "mass": "85.47 u",
    "state": "Sólido",
    "meltingPoint": "39.3 °C",
    "boilingPoint": "688 °C",
    "electronegativity": "0.82",
    "description": "Extremamente reativo, pode explodir ao contato com água e é usado em relógios atômicos."
  },
  {
    "number": 38,
    "name": "Estrôncio",
    "symbol": "Sr",
    "mass": "87.62 u",
    "state": "Sólido",
    "meltingPoint": "777 °C",
    "boilingPoint": "1377 °C",
    "electronegativity": "0.95",
    "description": "Responsável pela cor vermelha em fogos de artifício."
  },
  {
    "number": 39,
    "name": "Ítrio",
    "symbol": "Y",
    "mass": "88.91 u",
    "state": "Sólido",
    "meltingPoint": "1526 °C",
    "boilingPoint": "3345 °C",
    "electronegativity": "1.22",
    "description": "Usado em telas de TV e LEDs para produzir cores vivas."
  },
  {
    "number": 40,
    "name": "Zircônio",
    "symbol": "Zr",
    "mass": "91.22 u",
    "state": "Sólido",
    "meltingPoint": "1855 °C",
    "boilingPoint": "4409 °C",
    "electronegativity": "1.33",
    "description": "Muito resistente ao calor, usado em reatores nucleares e materiais cerâmicos."
  },
  {
    "number": 41,
    "name": "Nióbio",
    "symbol": "Nb",
    "mass": "92.91 u",
    "state": "Sólido",
    "meltingPoint": "2477 °C",
    "boilingPoint": "4744 °C",
    "electronegativity": "1.6",
    "description": "Torna o aço mais leve e resistente, sendo muito importante na indústria."
  },
  {
    "number": 42,
    "name": "Molibdênio",
    "symbol": "Mo",
    "mass": "95.95 u",
    "state": "Sólido",
    "meltingPoint": "2623 °C",
    "boilingPoint": "4639 °C",
    "electronegativity": "2.16",
    "description": "Resiste a altas temperaturas e é usado em ligas metálicas e fertilizantes."
  },
  {
    "number": 43,
    "name": "Tecnécio",
    "symbol": "Tc",
    "mass": "98 u",
    "state": "Sólido",
    "meltingPoint": "2157 °C",
    "boilingPoint": "4265 °C",
    "electronegativity": "1.9",
    "description": "Primeiro elemento artificial, usado em exames médicos."
  },
  {
    "number": 44,
    "name": "Rutênio",
    "symbol": "Ru",
    "mass": "101.07 u",
    "state": "Sólido",
    "meltingPoint": "2334 °C",
    "boilingPoint": "4150 °C",
    "electronegativity": "2.2",
    "description": "Metal resistente usado em eletrônica e joias."
  },
  {
    "number": 45,
    "name": "Ródio",
    "symbol": "Rh",
    "mass": "102.91 u",
    "state": "Sólido",
    "meltingPoint": "1964 °C",
    "boilingPoint": "3695 °C",
    "electronegativity": "2.28",
    "description": "Um dos metais mais caros, usado em catalisadores e joias."
  },
  {
    "number": 46,
    "name": "Paládio",
    "symbol": "Pd",
    "mass": "106.42 u",
    "state": "Sólido",
    "meltingPoint": "1554.9 °C",
    "boilingPoint": "2963 °C",
    "electronegativity": "2.20",
    "description": "Ajuda a reduzir a poluição dos carros em catalisadores."
  },
  {
    "number": 47,
    "name": "Prata",
    "symbol": "Ag",
    "mass": "107.87 u",
    "state": "Sólido",
    "meltingPoint": "961.8 °C",
    "boilingPoint": "2162 °C",
    "electronegativity": "1.93",
    "description": "Melhor condutor elétrico natural, usado em joias e eletrônicos."
  },
  {
    "number": 48,
    "name": "Cádmio",
    "symbol": "Cd",
    "mass": "112.41 u",
    "state": "Sólido",
    "meltingPoint": "321.1 °C",
    "boilingPoint": "767 °C",
    "electronegativity": "1.69",
    "description": "Usado em baterias e pigmentos coloridos."
  },
  {
    "number": 49,
    "name": "Índio",
    "symbol": "In",
    "mass": "114.82 u",
    "state": "Sólido",
    "meltingPoint": "156.6 °C",
    "boilingPoint": "2072 °C",
    "electronegativity": "1.78",
    "description": "Permite telas sensíveis ao toque funcionarem."
  },
  {
    "number": 50,
    "name": "Estanho",
    "symbol": "Sn",
    "mass": "118.71 u",
    "state": "Sólido",
    "meltingPoint": "231.9 °C",
    "boilingPoint": "2602 °C",
    "electronegativity": "1.96",
    "description": "Usado em soldas e ligas metálicas como o bronze."
  },
  {
    "number": 51,
    "name": "Antimônio",
    "symbol": "Sb",
    "mass": "121.76 u",
    "state": "Sólido",
    "meltingPoint": "630.6 °C",
    "boilingPoint": "1587 °C",
    "electronegativity": "2.05",
    "description": "Já foi usado em cosméticos antigos e hoje em baterias."
  },
  {
    "number": 52,
    "name": "Telúrio",
    "symbol": "Te",
    "mass": "127.60 u",
    "state": "Sólido",
    "meltingPoint": "449.5 °C",
    "boilingPoint": "988 °C",
    "electronegativity": "2.1",
    "description": "Elemento raro com cheiro de alho quando manipulado."
  },
  {
    "number": 53,
    "name": "Iodo",
    "symbol": "I",
    "mass": "126.90 u",
    "state": "Sólido",
    "meltingPoint": "113.7 °C",
    "boilingPoint": "184.3 °C",
    "electronegativity": "2.66",
    "description": "Essencial para o corpo humano e conhecido por seu vapor roxo."
  },
  {
    "number": 54,
    "name": "Xenônio",
    "symbol": "Xe",
    "mass": "131.29 u",
    "state": "Gasoso",
    "meltingPoint": "-111.8 °C",
    "boilingPoint": "-108.1 °C",
    "electronegativity": "2.60",
    "description": "Usado em faróis de carros e iluminação intensa."
  },
  {
    "number": 55,
    "name": "Césio",
    "symbol": "Cs",
    "mass": "132.91 u",
    "state": "Sólido",
    "meltingPoint": "28.5 °C",
    "boilingPoint": "671 °C",
    "electronegativity": "0.79",
    "description": "Base dos relógios mais precisos do mundo."
  },
  {
    "number": 56,
    "name": "Bário",
    "symbol": "Ba",
    "mass": "137.33 u",
    "state": "Sólido",
    "meltingPoint": "727 °C",
    "boilingPoint": "1870 °C",
    "electronegativity": "0.89",
    "description": "Usado em exames médicos de raio-X."
  },
  {
    "number": 57,
    "name": "Lantânio",
    "symbol": "La",
    "mass": "138.91 u",
    "state": "Sólido",
    "meltingPoint": "920 °C",
    "boilingPoint": "3464 °C",
    "electronegativity": "1.10",
    "description": "Usado em lentes ópticas e câmeras."
  },
  {
    "number": 58,
    "name": "Cério",
    "symbol": "Ce",
    "mass": "140.12 u",
    "state": "Sólido",
    "meltingPoint": "795 °C",
    "boilingPoint": "3443 °C",
    "electronegativity": "1.12",
    "description": "Produz faíscas e é usado em isqueiros."
  },
  {
    "number": 59,
    "name": "Praseodímio",
    "symbol": "Pr",
    "mass": "140.91 u",
    "state": "Sólido",
    "meltingPoint": "935 °C",
    "boilingPoint": "3520 °C",
    "electronegativity": "1.13",
    "description": "Usado em vidros especiais e proteção ocular."
  },
  {
    "number": 60,
    "name": "Neodímio",
    "symbol": "Nd",
    "mass": "144.24 u",
    "state": "Sólido",
    "meltingPoint": "1024 °C",
    "boilingPoint": "3074 °C",
    "electronegativity": "1.14",
    "description": "Cria os ímãs mais fortes usados em fones e motores elétricos."
  },
  {
    "number": 61,
    "name": "Promécio",
    "symbol": "Pm",
    "mass": "145 u",
    "state": "Sólido",
    "meltingPoint": "1042 °C",
    "boilingPoint": "3000 °C",
    "electronegativity": "1.13",
    "description": "Um elemento raro e radioativo que pode brilhar no escuro, usado em tintas luminosas."
  },
  {
    "number": 62,
    "name": "Samário",
    "symbol": "Sm",
    "mass": "150.36 u",
    "state": "Sólido",
    "meltingPoint": "1072 °C",
    "boilingPoint": "1794 °C",
    "electronegativity": "1.17",
    "description": "Usado para criar ímãs fortes que resistem a altas temperaturas."
  },
  {
    "number": 63,
    "name": "Európio",
    "symbol": "Eu",
    "mass": "151.96 u",
    "state": "Sólido",
    "meltingPoint": "826 °C",
    "boilingPoint": "1529 °C",
    "electronegativity": "1.2",
    "description": "Utilizado em notas de dinheiro e materiais que brilham sob luz negra."
  },
  {
    "number": 64,
    "name": "Gadolínio",
    "symbol": "Gd",
    "mass": "157.25 u",
    "state": "Sólido",
    "meltingPoint": "1312 °C",
    "boilingPoint": "3273 °C",
    "electronegativity": "1.20",
    "description": "Usado em exames de ressonância magnética para visualizar o interior do corpo."
  },
  {
    "number": 65,
    "name": "Térbio",
    "symbol": "Tb",
    "mass": "158.93 u",
    "state": "Sólido",
    "meltingPoint": "1356 °C",
    "boilingPoint": "3230 °C",
    "electronegativity": "1.2",
    "description": "Importante para LEDs e telas modernas."
  },
  {
    "number": 66,
    "name": "Disprósio",
    "symbol": "Dy",
    "mass": "162.50 u",
    "state": "Sólido",
    "meltingPoint": "1407 °C",
    "boilingPoint": "2567 °C",
    "electronegativity": "1.22",
    "description": "Ajuda a fabricar ímãs potentes usados em motores elétricos."
  },
  {
    "number": 67,
    "name": "Hólmio",
    "symbol": "Ho",
    "mass": "164.93 u",
    "state": "Sólido",
    "meltingPoint": "1474 °C",
    "boilingPoint": "2700 °C",
    "electronegativity": "1.23",
    "description": "Tem propriedades magnéticas muito fortes, usado em lasers."
  },
  {
    "number": 68,
    "name": "Érbio",
    "symbol": "Er",
    "mass": "167.26 u",
    "state": "Sólido",
    "meltingPoint": "1529 °C",
    "boilingPoint": "2868 °C",
    "electronegativity": "1.24",
    "description": "Essencial para fibras ópticas que levam internet de alta velocidade."
  },
  {
    "number": 69,
    "name": "Túlio",
    "symbol": "Tm",
    "mass": "168.93 u",
    "state": "Sólido",
    "meltingPoint": "1545 °C",
    "boilingPoint": "1950 °C",
    "electronegativity": "1.25",
    "description": "Usado em equipamentos portáteis de raio-X."
  },
  {
    "number": 70,
    "name": "Itérbio",
    "symbol": "Yb",
    "mass": "173.05 u",
    "state": "Sólido",
    "meltingPoint": "824 °C",
    "boilingPoint": "1196 °C",
    "electronegativity": "1.1",
    "description": "Utilizado em lasers e relógios atômicos."
  },
  {
    "number": 71,
    "name": "Lutécio",
    "symbol": "Lu",
    "mass": "174.97 u",
    "state": "Sólido",
    "meltingPoint": "1663 °C",
    "boilingPoint": "3402 °C",
    "electronegativity": "1.27",
    "description": "Usado em tecnologia médica e na indústria do petróleo."
  },
  {
    "number": 72,
    "name": "Háfnio",
    "symbol": "Hf",
    "mass": "178.49 u",
    "state": "Sólido",
    "meltingPoint": "2233 °C",
    "boilingPoint": "4603 °C",
    "electronegativity": "1.3",
    "description": "Importante em reatores nucleares e microchips."
  },
  {
    "number": 73,
    "name": "Tântalo",
    "symbol": "Ta",
    "mass": "180.95 u",
    "state": "Sólido",
    "meltingPoint": "3017 °C",
    "boilingPoint": "5458 °C",
    "electronegativity": "1.5",
    "description": "Muito resistente, usado em eletrônicos e implantes médicos."
  },
  {
    "number": 74,
    "name": "Tungstênio",
    "symbol": "W",
    "mass": "183.84 u",
    "state": "Sólido",
    "meltingPoint": "3422 °C",
    "boilingPoint": "5555 °C",
    "electronegativity": "2.36",
    "description": "Tem o maior ponto de fusão, usado em filamentos de lâmpadas."
  },
  {
    "number": 75,
    "name": "Rênio",
    "symbol": "Re",
    "mass": "186.21 u",
    "state": "Sólido",
    "meltingPoint": "3186 °C",
    "boilingPoint": "5596 °C",
    "electronegativity": "1.9",
    "description": "Resiste a calor extremo, usado em motores de jatos."
  },
  {
    "number": 76,
    "name": "Ósmio",
    "symbol": "Os",
    "mass": "190.23 u",
    "state": "Sólido",
    "meltingPoint": "3033 °C",
    "boilingPoint": "5012 °C",
    "electronegativity": "2.2",
    "description": "O metal mais denso da natureza, usado em ligas especiais."
  },
  {
    "number": 77,
    "name": "Irídio",
    "symbol": "Ir",
    "mass": "192.22 u",
    "state": "Sólido",
    "meltingPoint": "2446 °C",
    "boilingPoint": "4428 °C",
    "electronegativity": "2.2",
    "description": "Extremamente resistente à corrosão e altas temperaturas."
  },
  {
    "number": 78,
    "name": "Platina",
    "symbol": "Pt",
    "mass": "195.08 u",
    "state": "Sólido",
    "meltingPoint": "1768.3 °C",
    "boilingPoint": "3825 °C",
    "electronegativity": "2.28",
    "description": "Metal precioso usado em joias e catalisadores."
  },
  {
    "number": 79,
    "name": "Ouro",
    "symbol": "Au",
    "mass": "196.97 u",
    "state": "Sólido",
    "meltingPoint": "1064.2 °C",
    "boilingPoint": "2856 °C",
    "electronegativity": "2.54",
    "description": "Não enferruja e é usado em joias e eletrônicos."
  },
  {
    "number": 80,
    "name": "Mercúrio",
    "symbol": "Hg",
    "mass": "200.59 u",
    "state": "Líquido",
    "meltingPoint": "-38.8 °C",
    "boilingPoint": "356.7 °C",
    "electronegativity": "2.00",
    "description": "Metal líquido à temperatura ambiente, usado com cautela devido à toxicidade."
  },
  {
    "number": 81,
    "name": "Tálio",
    "symbol": "Tl",
    "mass": "204.38 u",
    "state": "Sólido",
    "meltingPoint": "304 °C",
    "boilingPoint": "1473 °C",
    "electronegativity": "1.62",
    "description": "Metal tóxico usado em eletrônica e já presente em venenos."
  },
  {
    "number": 82,
    "name": "Chumbo",
    "symbol": "Pb",
    "mass": "207.2 u",
    "state": "Sólido",
    "meltingPoint": "327.5 °C",
    "boilingPoint": "1749 °C",
    "electronegativity": "2.33",
    "description": "Protege contra radiação, usado em baterias e blindagem."
  },
  {
    "number": 83,
    "name": "Bismuto",
    "symbol": "Bi",
    "mass": "208.98 u",
    "state": "Sólido",
    "meltingPoint": "271.4 °C",
    "boilingPoint": "1564 °C",
    "electronegativity": "2.02",
    "description": "Forma cristais coloridos e é usado em medicamentos."
  },
  {
    "number": 84,
    "name": "Polônio",
    "symbol": "Po",
    "mass": "209 u",
    "state": "Sólido",
    "meltingPoint": "254 °C",
    "boilingPoint": "962 °C",
    "electronegativity": "2.0",
    "description": "Altamente radioativo, descoberto por Marie Curie."
  },
  {
    "number": 85,
    "name": "Astato",
    "symbol": "At",
    "mass": "210 u",
    "state": "Sólido",
    "meltingPoint": "302 °C",
    "boilingPoint": "337 °C",
    "electronegativity": "2.2",
    "description": "Extremamente raro e radioativo."
  },
  {
    "number": 86,
    "name": "Radônio",
    "symbol": "Rn",
    "mass": "222 u",
    "state": "Gasoso",
    "meltingPoint": "-71 °C",
    "boilingPoint": "-61.7 °C",
    "electronegativity": "N/A",
    "description": "Gás radioativo natural que pode acumular em ambientes fechados."
  },
  {
    "number": 87,
    "name": "Frâncio",
    "symbol": "Fr",
    "mass": "223 u",
    "state": "Sólido",
    "meltingPoint": "27 °C",
    "boilingPoint": "677 °C",
    "electronegativity": "0.7",
    "description": "Um dos elementos mais raros e instáveis da Terra."
  },
  {
    "number": 88,
    "name": "Rádio",
    "symbol": "Ra",
    "mass": "226 u",
    "state": "Sólido",
    "meltingPoint": "700 °C",
    "boilingPoint": "1737 °C",
    "electronegativity": "0.9",
    "description": "Altamente radioativo, já foi usado em tintas luminosas."
  },
  {
    "number": 89,
    "name": "Actínio",
    "symbol": "Ac",
    "mass": "227 u",
    "state": "Sólido",
    "meltingPoint": "1050 °C",
    "boilingPoint": "3200 °C",
    "electronegativity": "1.1",
    "description": "Brilha com luz azul em ambientes escuros devido à radioatividade."
  },
  {
    "number": 90,
    "name": "Tório",
    "symbol": "Th",
    "mass": "232.04 u",
    "state": "Sólido",
    "meltingPoint": "1750 °C",
    "boilingPoint": "4788 °C",
    "electronegativity": "1.3",
    "description": "Pode ser usado como combustível nuclear alternativo."
  },
  {
    "number": 91,
    "name": "Protactínio",
    "symbol": "Pa",
    "mass": "231.04 u",
    "state": "Sólido",
    "meltingPoint": "1568 °C",
    "boilingPoint": "4027 °C",
    "electronegativity": "1.5",
    "description": "Elemento raro e altamente radioativo encontrado junto ao urânio."
  },
  {
    "number": 92,
    "name": "Urânio",
    "symbol": "U",
    "mass": "238.03 u",
    "state": "Sólido",
    "meltingPoint": "1132.2 °C",
    "boilingPoint": "4131 °C",
    "electronegativity": "1.38",
    "description": "Fonte de energia nuclear usada em usinas para gerar eletricidade."
  },
  {
    "number": 93,
    "name": "Netúnio",
    "symbol": "Np",
    "mass": "237 u",
    "state": "Sólido",
    "meltingPoint": "644 °C",
    "boilingPoint": "4000 °C",
    "electronegativity": "1.36",
    "description": "Primeiro elemento sintético após o urânio, usado em pesquisas nucleares."
  },
  {
    "number": 94,
    "name": "Plutônio",
    "symbol": "Pu",
    "mass": "244 u",
    "state": "Sólido",
    "meltingPoint": "639.4 °C",
    "boilingPoint": "3228 °C",
    "electronegativity": "1.28",
    "description": "Elemento radioativo usado em energia nuclear e missões espaciais."
  },
  {
    "number": 95,
    "name": "Amerício",
    "symbol": "Am",
    "mass": "243 u",
    "state": "Sólido",
    "meltingPoint": "1176 °C",
    "boilingPoint": "2607 °C",
    "electronegativity": "1.3",
    "description": "Presente em detectores de fumaça domésticos."
  },
  {
    "number": 96,
    "name": "Cúrio",
    "symbol": "Cm",
    "mass": "247 u",
    "state": "Sólido",
    "meltingPoint": "1345 °C",
    "boilingPoint": "3110 °C",
    "electronegativity": "1.3",
    "description": "Usado em equipamentos científicos e exploração espacial."
  },
  {
    "number": 97,
    "name": "Berquélio",
    "symbol": "Bk",
    "mass": "247 u",
    "state": "Sólido",
    "meltingPoint": "986 °C",
    "boilingPoint": "2627 °C",
    "electronegativity": "1.3",
    "description": "Elemento sintético criado em laboratório para pesquisa."
  },
  {
    "number": 98,
    "name": "Califórnio",
    "symbol": "Cf",
    "mass": "251 u",
    "state": "Sólido",
    "meltingPoint": "900 °C",
    "boilingPoint": "1470 °C",
    "electronegativity": "1.3",
    "description": "Muito caro e usado para detectar falhas em materiais."
  },
  {
    "number": 99,
    "name": "Einstênio",
    "symbol": "Es",
    "mass": "252 u",
    "state": "Sólido",
    "meltingPoint": "860 °C",
    "boilingPoint": "996 °C",
    "electronegativity": "1.3",
    "description": "Criado em explosões nucleares e nomeado em homenagem a Einstein."
  },
  {
    "number": 100,
    "name": "Férmio",
    "symbol": "Fm",
    "mass": "257 u",
    "state": "Sólido",
    "meltingPoint": "1527 °C",
    "boilingPoint": "N/A",
    "electronegativity": "1.3",
    "description": "Elemento sintético produzido em reações nucleares."
  },
  {
    "number": 101,
    "name": "Mendelévio",
    "symbol": "Md",
    "mass": "258 u",
    "state": "Sólido",
    "meltingPoint": "827 °C",
    "boilingPoint": "N/A",
    "electronegativity": "1.3",
    "description": "Nomeado em homenagem ao criador da tabela periódica."
  },
  {
    "number": 102,
    "name": "Nobélio",
    "symbol": "No",
    "mass": "259 u",
    "state": "Sólido",
    "meltingPoint": "827 °C",
    "boilingPoint": "N/A",
    "electronegativity": "1.3",
    "description": "Homenagem a Alfred Nobel, ligado à pesquisa científica."
  },
  {
    "number": 103,
    "name": "Laurêncio",
    "symbol": "Lr",
    "mass": "266 u",
    "state": "Sólido",
    "meltingPoint": "1627 °C",
    "boilingPoint": "N/A",
    "electronegativity": "1.3",
    "description": "Último dos actinídeos, criado em laboratório."
  },
  {
    "number": 104,
    "name": "Rutherfórdio",
    "symbol": "Rf",
    "mass": "267 u",
    "state": "Sólido",
    "meltingPoint": "2100 °C",
    "boilingPoint": "5500 °C",
    "electronegativity": "N/A",
    "description": "Elemento sintético nomeado em homenagem a Rutherford."
  },
  {
    "number": 105,
    "name": "Dúbnio",
    "symbol": "Db",
    "mass": "268 u",
    "state": "Sólido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Criado em laboratório e usado apenas em pesquisa científica."
  },
  {
    "number": 106,
    "name": "Seabórgio",
    "symbol": "Sg",
    "mass": "269 u",
    "state": "Sólido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Nomeado em homenagem a Glenn Seaborg."
  },
  {
    "number": 107,
    "name": "Bóhrio",
    "symbol": "Bh",
    "mass": "270 u",
    "state": "Sólido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Homenagem ao físico Niels Bohr."
  },
  {
    "number": 108,
    "name": "Hássio",
    "symbol": "Hs",
    "mass": "269 u",
    "state": "Sólido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Nomeado em homenagem à região alemã de Hesse."
  },
  {
    "number": 109,
    "name": "Meitnério",
    "symbol": "Mt",
    "mass": "278 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Homenagem à cientista Lise Meitner."
  },
  {
    "number": 110,
    "name": "Darmstátio",
    "symbol": "Ds",
    "mass": "281 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Recebeu o nome da cidade onde foi descoberto."
  },
  {
    "number": 111,
    "name": "Roentgênio",
    "symbol": "Rg",
    "mass": "282 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Homenagem ao descobridor dos raios X."
  },
  {
    "number": 112,
    "name": "Copérnico",
    "symbol": "Cn",
    "mass": "285 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Nomeado em homenagem ao astrônomo Copérnico."
  },
  {
    "number": 113,
    "name": "Nihônio",
    "symbol": "Nh",
    "mass": "286 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Primeiro elemento nomeado no Japão."
  },
  {
    "number": 114,
    "name": "Fleróvio",
    "symbol": "Fl",
    "mass": "289 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Nomeado em homenagem a um físico russo."
  },
  {
    "number": 115,
    "name": "Moscóvio",
    "symbol": "Mc",
    "mass": "290 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Homenagem à região de Moscou."
  },
  {
    "number": 116,
    "name": "Livermório",
    "symbol": "Lv",
    "mass": "293 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Nomeado após laboratório dos EUA."
  },
  {
    "number": 117,
    "name": "Tenesso",
    "symbol": "Ts",
    "mass": "294 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Homenagem ao estado do Tennessee."
  },
  {
    "number": 118,
    "name": "Oganessônio",
    "symbol": "Og",
    "mass": "294 u",
    "state": "Desconhecido",
    "meltingPoint": "N/A",
    "boilingPoint": "N/A",
    "electronegativity": "N/A",
    "description": "Nomeado em homenagem a Yuri Oganessian, pesquisador de elementos superpesados."
  }
]